discord:
  production: true
  token: t0ken
  locales:
    error:
      zhCN: 出错啦
      enUS: Error
      jaJP: エラー
      koKR: 에러
    empty_response:
      zhCN: 看来我离 OpenAI 还有点远，我先休息一下吧。
      enUS: It seems I'm still far away from OpenAI, I'll take a break.
      jaJP: OpenAIとの距離がまだ遠いようです。ちょっと休憩します。
      koKR: OpenAI와의 거리가 아직 멀어보여요. 잠시 쉬겠습니다.
    no_choice:
      zhCN: 针对这个问题, OpenAI 表示无可奉告!
      enUS: OpenAI has nothing to talk about this!
      jaJP: この問題についてOpenAIは何も言えません！
      koKR: OpenAI는 이에 대해 말할 게 없어요!
    cleared:
      zhCN: 上下文已清空。
      enUS: Context cleared.
      jaJP: コンテキストがクリアされました。
      koKR: 컨텍스트가 초기화되었습니다.
    clear_context:
      zhCN: 我已经忘记了之前的对话。
      enUS: I've forgotten the previous conversation.
      jaJP: 以前の会話を忘れました。
      koKR: 이전 대화를 잊었습니다.
    token_limit_reached:
      zhCN: Token 数量已达上限，请缩减你的提示。
      enUS: Token limit reached, please shorten your prompt.
      jaJP: トークン数の上限に達しました。プロンプトを短くしてください。
      koKR: 토큰 한도에 도달했습니다. 프롬프트를 줄여주세요。
  servers:
    - id: 123456
      language: zhCN
      chat_channels:
        - id: 123456
          prompt_token_limit: 1800
          completion_token_limit: 2000
      commands:
        clear_context:
          enable: true
          aliases:
            - clear
    - id: 1234567
      language: enUS
      chat_channels:
        - id: 1234567
          prompt_token_limit: 1800
          completion_token_limit: 2000
      commands:
        clear_context:
          enable: true
          aliases:
            - clear
            - cc
openai:
  token: t0ken
  model_id: gpt-3.5-turbo-0301
  token_prediction_model_id: gpt-3.5-turbo